#!/bin/sh

echo ""

# Run formatting
python3 morphs.py format

# Run validation
python3 morphs.py validate
success=$?

# Don't commit if morph validation fails
if [ $success -eq 0 ]; then
	exit 0
else
	echo "=== DID NOT COMMIT ==="
	echo ""
	exit 1
fi
