#!/bin/sh

echo ""

# Run formatting
python3 morphs.py format
files_changed=$?

# Don't commit if formatting altered any files
if [ $files_changed -eq 0 ]; then
	true
else
	echo ""
	echo "=== DID NOT COMMIT ==="
	echo ""
	exit 1
fi

# Run validation
python3 morphs.py validate
validate_success=$?

# Don't commit if morph validation fails
if [ $validate_success -eq 0 ]; then
	true
else
	echo "=== DID NOT COMMIT ==="
	echo ""
	exit 1
fi

# Run linter
python3 linter.py -r src
linter_success=$?

# Don't commit if linter shows errors or edits code
if [ $linter_success -eq 0 ]; then
	exit 0
else
	echo "=== DID NOT COMMIT ==="
	echo ""
	exit 1
fi
